[app]
name = "claude-code-usage-rs"
version = "0.1.0"
debug = false
verbose = false
data_dir = "./data"
cache_dir = "./cache"
config_dir = "./config"

[data_source]
default_source = "file"
source_paths = { default = "./test_data.json" }
api_endpoints = { default = "http://localhost:8080/api" }
pricing_data_path = "./pricing.json"
auto_refresh_interval = 3600

[output]
default_format = "table"
output_dir = "./output"

[output.table]
max_width = 120
enable_colors = true
compact = false

[output.chart]
enable_charts = false
width = 80
height = 20
theme = "default"

[budget]
monthly_limit = 100.0
currency = "USD"
warning_threshold = 80.0
alert_threshold = 95.0
enable_alerts = true

[mcp]
enabled = false
host = "localhost"
port = 8080
enable_auth = false
allowed_origins = ["*"]

[logging]
level = "info"
enable_file_logging = false
json_format = false
colored = true
log_dir = "./logs"
max_log_size = 10485760
max_log_files = 5

[cache]
enabled = true
expiration = 3600
max_size = 104857600
cleanup_interval = 1800